version: "3.9"

services:

  app:
    build: .
    container_name: fastapi_app

    ports:
      - "8000:8000"

    depends_on:
      - db

    volumes:
      - .:/app

    restart: always

  db:
    image: mysql:8.0
    container_name: mysql_db

    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}

    ports:
      - "3307:3306"

    restart: always